[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "npm start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200